# -*- encoding: utf-8 -*-

=begin
#Jamf Pro API

### Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

The version of the OpenAPI document: production

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "ruby-jamf-pro-api-client/version"

Gem::Specification.new do |s|
  s.name        = "ruby-jamf-pro-api-client"
  s.version     = JamfPro::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["hiboma"]
  s.email       = ["hiroyan@gmail.com"]
  s.homepage    = "https://github.com/hiboma/ruby-jamf-pro-api-client"
  s.summary     = "Jamf Pro API Client Gem"
  s.description = "Jamf Pro API Client Gem"
  s.license     = "MIT"
  s.required_ruby_version = ">= 3.1"

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
