=begin
#Jamf Pro API

### Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

The version of the OpenAPI document: production

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'date'
require 'time'

module JamfPro
  # will be populated if the type is android.
  class AndroidDetails
    attr_accessor :os_name

    attr_accessor :manufacturer

    attr_accessor :model

    attr_accessor :internal_capacity_mb

    attr_accessor :internal_available_mb

    attr_accessor :internal_percent_used

    attr_accessor :external_capacity_mb

    attr_accessor :external_available_mb

    attr_accessor :external_percent_used

    attr_accessor :battery_level

    attr_accessor :last_backup_timestamp

    attr_accessor :api_version

    attr_accessor :computer

    attr_accessor :security

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'os_name' => :'osName',
        :'manufacturer' => :'manufacturer',
        :'model' => :'model',
        :'internal_capacity_mb' => :'internalCapacityMb',
        :'internal_available_mb' => :'internalAvailableMb',
        :'internal_percent_used' => :'internalPercentUsed',
        :'external_capacity_mb' => :'externalCapacityMb',
        :'external_available_mb' => :'externalAvailableMb',
        :'external_percent_used' => :'externalPercentUsed',
        :'battery_level' => :'batteryLevel',
        :'last_backup_timestamp' => :'lastBackupTimestamp',
        :'api_version' => :'apiVersion',
        :'computer' => :'computer',
        :'security' => :'security'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'os_name' => :'String',
        :'manufacturer' => :'String',
        :'model' => :'String',
        :'internal_capacity_mb' => :'Integer',
        :'internal_available_mb' => :'Integer',
        :'internal_percent_used' => :'Integer',
        :'external_capacity_mb' => :'Integer',
        :'external_available_mb' => :'Integer',
        :'external_percent_used' => :'Integer',
        :'battery_level' => :'Integer',
        :'last_backup_timestamp' => :'Time',
        :'api_version' => :'Integer',
        :'computer' => :'IdAndName',
        :'security' => :'Security'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `JamfPro::AndroidDetails` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `JamfPro::AndroidDetails`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'os_name')
        self.os_name = attributes[:'os_name']
      end

      if attributes.key?(:'manufacturer')
        self.manufacturer = attributes[:'manufacturer']
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.key?(:'internal_capacity_mb')
        self.internal_capacity_mb = attributes[:'internal_capacity_mb']
      end

      if attributes.key?(:'internal_available_mb')
        self.internal_available_mb = attributes[:'internal_available_mb']
      end

      if attributes.key?(:'internal_percent_used')
        self.internal_percent_used = attributes[:'internal_percent_used']
      end

      if attributes.key?(:'external_capacity_mb')
        self.external_capacity_mb = attributes[:'external_capacity_mb']
      end

      if attributes.key?(:'external_available_mb')
        self.external_available_mb = attributes[:'external_available_mb']
      end

      if attributes.key?(:'external_percent_used')
        self.external_percent_used = attributes[:'external_percent_used']
      end

      if attributes.key?(:'battery_level')
        self.battery_level = attributes[:'battery_level']
      end

      if attributes.key?(:'last_backup_timestamp')
        self.last_backup_timestamp = attributes[:'last_backup_timestamp']
      end

      if attributes.key?(:'api_version')
        self.api_version = attributes[:'api_version']
      end

      if attributes.key?(:'computer')
        self.computer = attributes[:'computer']
      end

      if attributes.key?(:'security')
        self.security = attributes[:'security']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          os_name == o.os_name &&
          manufacturer == o.manufacturer &&
          model == o.model &&
          internal_capacity_mb == o.internal_capacity_mb &&
          internal_available_mb == o.internal_available_mb &&
          internal_percent_used == o.internal_percent_used &&
          external_capacity_mb == o.external_capacity_mb &&
          external_available_mb == o.external_available_mb &&
          external_percent_used == o.external_percent_used &&
          battery_level == o.battery_level &&
          last_backup_timestamp == o.last_backup_timestamp &&
          api_version == o.api_version &&
          computer == o.computer &&
          security == o.security
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [os_name, manufacturer, model, internal_capacity_mb, internal_available_mb, internal_percent_used, external_capacity_mb, external_available_mb, external_percent_used, battery_level, last_backup_timestamp, api_version, computer, security].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = JamfPro.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
