=begin
#Jamf Pro API

### Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

The version of the OpenAPI document: production

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'date'
require 'time'

module JamfPro
  class NetworkV2
    attr_accessor :cellular_technology

    attr_accessor :voice_roaming_enabled

    attr_accessor :imei

    attr_accessor :iccid

    attr_accessor :meid

    # EID or \"embedded identity document\" is a number associated with the eSIM on a device
    attr_accessor :eid

    attr_accessor :carrier_settings_version

    attr_accessor :current_carrier_network

    attr_accessor :current_mobile_country_code

    attr_accessor :current_mobile_network_code

    attr_accessor :home_carrier_network

    attr_accessor :home_mobile_country_code

    attr_accessor :home_mobile_network_code

    attr_accessor :data_roaming_enabled

    attr_accessor :roaming

    attr_accessor :personal_hotspot_enabled

    attr_accessor :phone_number

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'cellular_technology' => :'cellularTechnology',
        :'voice_roaming_enabled' => :'voiceRoamingEnabled',
        :'imei' => :'imei',
        :'iccid' => :'iccid',
        :'meid' => :'meid',
        :'eid' => :'eid',
        :'carrier_settings_version' => :'carrierSettingsVersion',
        :'current_carrier_network' => :'currentCarrierNetwork',
        :'current_mobile_country_code' => :'currentMobileCountryCode',
        :'current_mobile_network_code' => :'currentMobileNetworkCode',
        :'home_carrier_network' => :'homeCarrierNetwork',
        :'home_mobile_country_code' => :'homeMobileCountryCode',
        :'home_mobile_network_code' => :'homeMobileNetworkCode',
        :'data_roaming_enabled' => :'dataRoamingEnabled',
        :'roaming' => :'roaming',
        :'personal_hotspot_enabled' => :'personalHotspotEnabled',
        :'phone_number' => :'phoneNumber'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'cellular_technology' => :'String',
        :'voice_roaming_enabled' => :'Boolean',
        :'imei' => :'String',
        :'iccid' => :'String',
        :'meid' => :'String',
        :'eid' => :'String',
        :'carrier_settings_version' => :'String',
        :'current_carrier_network' => :'String',
        :'current_mobile_country_code' => :'String',
        :'current_mobile_network_code' => :'String',
        :'home_carrier_network' => :'String',
        :'home_mobile_country_code' => :'String',
        :'home_mobile_network_code' => :'String',
        :'data_roaming_enabled' => :'Boolean',
        :'roaming' => :'Boolean',
        :'personal_hotspot_enabled' => :'Boolean',
        :'phone_number' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `JamfPro::NetworkV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `JamfPro::NetworkV2`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'cellular_technology')
        self.cellular_technology = attributes[:'cellular_technology']
      end

      if attributes.key?(:'voice_roaming_enabled')
        self.voice_roaming_enabled = attributes[:'voice_roaming_enabled']
      end

      if attributes.key?(:'imei')
        self.imei = attributes[:'imei']
      end

      if attributes.key?(:'iccid')
        self.iccid = attributes[:'iccid']
      end

      if attributes.key?(:'meid')
        self.meid = attributes[:'meid']
      end

      if attributes.key?(:'eid')
        self.eid = attributes[:'eid']
      end

      if attributes.key?(:'carrier_settings_version')
        self.carrier_settings_version = attributes[:'carrier_settings_version']
      end

      if attributes.key?(:'current_carrier_network')
        self.current_carrier_network = attributes[:'current_carrier_network']
      end

      if attributes.key?(:'current_mobile_country_code')
        self.current_mobile_country_code = attributes[:'current_mobile_country_code']
      end

      if attributes.key?(:'current_mobile_network_code')
        self.current_mobile_network_code = attributes[:'current_mobile_network_code']
      end

      if attributes.key?(:'home_carrier_network')
        self.home_carrier_network = attributes[:'home_carrier_network']
      end

      if attributes.key?(:'home_mobile_country_code')
        self.home_mobile_country_code = attributes[:'home_mobile_country_code']
      end

      if attributes.key?(:'home_mobile_network_code')
        self.home_mobile_network_code = attributes[:'home_mobile_network_code']
      end

      if attributes.key?(:'data_roaming_enabled')
        self.data_roaming_enabled = attributes[:'data_roaming_enabled']
      end

      if attributes.key?(:'roaming')
        self.roaming = attributes[:'roaming']
      end

      if attributes.key?(:'personal_hotspot_enabled')
        self.personal_hotspot_enabled = attributes[:'personal_hotspot_enabled']
      end

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          cellular_technology == o.cellular_technology &&
          voice_roaming_enabled == o.voice_roaming_enabled &&
          imei == o.imei &&
          iccid == o.iccid &&
          meid == o.meid &&
          eid == o.eid &&
          carrier_settings_version == o.carrier_settings_version &&
          current_carrier_network == o.current_carrier_network &&
          current_mobile_country_code == o.current_mobile_country_code &&
          current_mobile_network_code == o.current_mobile_network_code &&
          home_carrier_network == o.home_carrier_network &&
          home_mobile_country_code == o.home_mobile_country_code &&
          home_mobile_network_code == o.home_mobile_network_code &&
          data_roaming_enabled == o.data_roaming_enabled &&
          roaming == o.roaming &&
          personal_hotspot_enabled == o.personal_hotspot_enabled &&
          phone_number == o.phone_number
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [cellular_technology, voice_roaming_enabled, imei, iccid, meid, eid, carrier_settings_version, current_carrier_network, current_mobile_country_code, current_mobile_network_code, home_carrier_network, home_mobile_country_code, home_mobile_network_code, data_roaming_enabled, roaming, personal_hotspot_enabled, phone_number].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = JamfPro.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
