=begin
#Jamf Pro API

### Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

The version of the OpenAPI document: production

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for JamfPro::CloudLdapApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CloudLdapApi' do
  before do
    # run before each test
    @api_instance = JamfPro::CloudLdapApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CloudLdapApi' do
    it 'should create an instance of CloudLdapApi' do
      expect(@api_instance).to be_instance_of(JamfPro::CloudLdapApi)
    end
  end

  # unit tests for v1_ldap_keystore_verify_post
  # Validate keystore for Cloud Identity Provider secure connection
  # Validate keystore for Cloud Identity Provider secure connection
  # @param cloud_ldap_keystore_file 
  # @param [Hash] opts the optional parameters
  # @return [CloudLdapKeystore]
  describe 'v1_ldap_keystore_verify_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_cloud_ldaps_defaults_provider_mappings_get
  # Get default mappings
  # Get default mappings for Cloud Identity Provider Provider.
  # @param provider Cloud Identity Provider name
  # @param [Hash] opts the optional parameters
  # @return [CloudLdapMappingsResponse]
  describe 'v2_cloud_ldaps_defaults_provider_mappings_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_cloud_ldaps_defaults_provider_server_configuration_get
  # Get default server configuration
  # Get default server configuration for Cloud Identity Provider Identity Provider.
  # @param provider Cloud Identity Provider name
  # @param [Hash] opts the optional parameters
  # @return [CloudLdapServerResponse]
  describe 'v2_cloud_ldaps_defaults_provider_server_configuration_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_cloud_ldaps_id_connection_bind_get
  # Get bind connection pool statistics
  # Get all search connection pool for chosen Cloud Identity Provider. numConnectionsClosedDefunct - The number of connections that have been closed as defunct. numConnectionsClosedExpired - The number of connections that have been closed because they were expired. numConnectionsClosedUnneeded - The number of connections that have been closed because they were no longer needed. numFailedCheckouts - The number of failed attempts to check out a connection from the pool. numFailedConnectionAttempts - The number of failed attempts to create a connection for use in the pool. numReleasedValid - The number of valid connections released back to the pool. numSuccessfulCheckouts - The number of successful attempts to check out a connection from the pool. numSuccessfulCheckoutsNewConnection - The number of successful checkout attempts that had to create a new connection because none were available. numSuccessfulConnectionAttempts - The number successful attempts to create a connection for use in the pool. maximumAvailableConnections - The maximum number of connections that may be available in the pool at any time. numSuccessfulCheckoutsWithoutWait - The number of successful checkout attempts that were able to take an existing connection without waiting. numSuccessfulCheckoutsAfterWait - The number of successful checkout attempts that retrieved a connection from the pool after waiting for it to become available. numAvailableConnections - The number of connections currently available for use in the pool. 
  # @param id Cloud Identity Provider identifier
  # @param [Hash] opts the optional parameters
  # @return [CloudLdapConnectionPoolStatistics]
  describe 'v2_cloud_ldaps_id_connection_bind_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_cloud_ldaps_id_connection_search_get
  # Get search connection pool statistics
  # Get all search connection pool for chosen Cloud Identity Provider. numConnectionsClosedDefunct - The number of connections that have been closed as defunct. numConnectionsClosedExpired - The number of connections that have been closed because they were expired. numConnectionsClosedUnneeded - The number of connections that have been closed because they were no longer needed. numFailedCheckouts - The number of failed attempts to check out a connection from the pool. numFailedConnectionAttempts - The number of failed attempts to create a connection for use in the pool. numReleasedValid - The number of valid connections released back to the pool. numSuccessfulCheckouts - The number of successful attempts to check out a connection from the pool. numSuccessfulCheckoutsNewConnection - The number of successful checkout attempts that had to create a new connection because none were available. numSuccessfulConnectionAttempts - The number successful attempts to create a connection for use in the pool. maximumAvailableConnections - The maximum number of connections that may be available in the pool at any time. numSuccessfulCheckoutsWithoutWait - The number of successful checkout attempts that were able to take an existing connection without waiting. numSuccessfulCheckoutsAfterWait - The number of successful checkout attempts that retrieved a connection from the pool after waiting for it to become available. numAvailableConnections - The number of connections currently available for use in the pool. 
  # @param id Cloud Identity Provider identifier
  # @param [Hash] opts the optional parameters
  # @return [CloudLdapConnectionPoolStatistics]
  describe 'v2_cloud_ldaps_id_connection_search_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_cloud_ldaps_id_connection_status_get
  # Tests the communication with the specified cloud connection 
  # Tests the communication with the specified cloud connection 
  # @param id Cloud Identity Provider identifier
  # @param [Hash] opts the optional parameters
  # @return [CloudLdapConnectionStatus]
  describe 'v2_cloud_ldaps_id_connection_status_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_cloud_ldaps_id_delete
  # Delete Cloud Identity Provider configuration.
  # Delete Cloud Identity Provider configuration.
  # @param id Cloud Identity Provider identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_cloud_ldaps_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_cloud_ldaps_id_get
  # Get Cloud Identity Provider configuration with given id.
  # Get Cloud Identity Provider configuration with given id.
  # @param id Cloud Identity Provider identifier
  # @param [Hash] opts the optional parameters
  # @return [LdapConfigurationResponse]
  describe 'v2_cloud_ldaps_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_cloud_ldaps_id_mappings_get
  # Get mappings configurations for Cloud Identity Providers server configuration.
  # Get all mappings configurations for Cloud Identity Providers server configuration.
  # @param id Cloud Identity Provider identifier
  # @param [Hash] opts the optional parameters
  # @return [CloudLdapMappingsResponse]
  describe 'v2_cloud_ldaps_id_mappings_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_cloud_ldaps_id_mappings_put
  # Update Cloud Identity Provider mappings configuration.
  # Update Cloud Identity Provider mappings configuration. Cannot be used for partial updates, all content body must be sent.
  # @param id Cloud Identity Provider identifier
  # @param cloud_ldap_mappings_request Cloud Identity Provider mappings to update.
  # @param [Hash] opts the optional parameters
  # @return [CloudLdapMappingsResponse]
  describe 'v2_cloud_ldaps_id_mappings_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_cloud_ldaps_id_put
  # Update Cloud Identity Provider configuration
  # Update Cloud Identity Provider configuration. Cannot be used for partial updates, all content body must be sent.
  # @param id Cloud Identity Provider identifier
  # @param ldap_configuration_update Cloud Identity Provider configuration to update
  # @param [Hash] opts the optional parameters
  # @return [LdapConfigurationResponse]
  describe 'v2_cloud_ldaps_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_cloud_ldaps_post
  # Create Cloud Identity Provider configuration
  # Create new Cloud Identity Provider configuration with unique display name. If mappings not provided, then defaults will be generated instead.
  # @param ldap_configuration_request Cloud Identity Provider configuration to create
  # @param [Hash] opts the optional parameters
  # @return [HrefResponse]
  describe 'v2_cloud_ldaps_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
