=begin
#Jamf Pro API

### Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

The version of the OpenAPI document: production

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for JamfPro::DepartmentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DepartmentsApi' do
  before do
    # run before each test
    @api_instance = JamfPro::DepartmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DepartmentsApi' do
    it 'should create an instance of DepartmentsApi' do
      expect(@api_instance).to be_instance_of(JamfPro::DepartmentsApi)
    end
  end

  # unit tests for v1_departments_delete_multiple_post
  # Deletes all departments by ids passed in body 
  # Deletes all departments by ids passed in body 
  # @param ids ids of departments to be deleted. pass in an array of ids
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_departments_delete_multiple_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_departments_get
  # Search for Departments 
  # Search for Departments 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [Array<String>] :sort Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Example: sort&#x3D;date:desc,name:asc 
  # @option opts [String] :filter Query in the RSQL format, allowing to filter department collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: id, name. Example: name&#x3D;&#x3D;\&quot;*department*\&quot;
  # @return [DepartmentsSearchResults]
  describe 'v1_departments_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_departments_id_delete
  # Remove specified department record 
  # Removes specified department record 
  # @param id instance id of department record
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_departments_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_departments_id_get
  # Get specified Department object 
  # Gets specified Department object 
  # @param id instance id of department record
  # @param [Hash] opts the optional parameters
  # @return [Department]
  describe 'v1_departments_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_departments_id_history_get
  # Get specified Department history object 
  # Gets specified Department history object 
  # @param id instance id of department history record
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [Array<String>] :sort Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort&#x3D;date:desc,name:asc 
  # @option opts [String] :filter Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: username, date, note, details. This param can be combined with paging and sorting. Example: filter&#x3D;username!&#x3D;admin and details&#x3D;&#x3D;*disabled* and date&lt;2019-12-15
  # @return [HistorySearchResults]
  describe 'v1_departments_id_history_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_departments_id_history_post
  # Add specified Department history object notes 
  # Adds specified Department history object notes 
  # @param id instance id of department history record
  # @param object_history_note history notes to create
  # @param [Hash] opts the optional parameters
  # @return [HrefResponse]
  describe 'v1_departments_id_history_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_departments_id_put
  # Update specified department object 
  # Update specified department object 
  # @param id instance id of department record
  # @param department department object to create. ids defined in this body will be ignored
  # @param [Hash] opts the optional parameters
  # @return [Department]
  describe 'v1_departments_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_departments_post
  # Create department record 
  # Create department record 
  # @param department department object to create. ids defined in this body will be ignored
  # @param [Hash] opts the optional parameters
  # @return [HrefResponse]
  describe 'v1_departments_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
