=begin
#Jamf Pro API

### Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

The version of the OpenAPI document: production

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for JamfPro::JamfProNotificationsPreviewApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JamfProNotificationsPreviewApi' do
  before do
    # run before each test
    @api_instance = JamfPro::JamfProNotificationsPreviewApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JamfProNotificationsPreviewApi' do
    it 'should create an instance of JamfProNotificationsPreviewApi' do
      expect(@api_instance).to be_instance_of(JamfPro::JamfProNotificationsPreviewApi)
    end
  end

  # unit tests for notifications_alerts_get
  # Get Notifications for user and site 
  # Gets notifications for user and site 
  # @param [Hash] opts the optional parameters
  # @return [Array<Notification>]
  describe 'notifications_alerts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for notifications_alerts_id_delete
  # DEPRECATED - USE \&quot;alerts/{type}/{id}\&quot; INSTEAD. Deletes only Patch Management notifications. 
  # DEPRECATED - USE \&quot;alerts/{type}/{id}\&quot; INSTEAD. Deletes only Patch Management notifications. 
  # @param id instance ID of the notification
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'notifications_alerts_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for notifications_alerts_type_id_delete
  # Delete Notifications 
  # Deletes notifications. Option for &#39;type&#39; is &#39;PATCH_UPDATE&#39;. 
  # @param id instance ID of the notification
  # @param type type of the notification
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'notifications_alerts_type_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
