=begin
#Jamf Pro API

### Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

The version of the OpenAPI document: production

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for JamfPro::JamfProVersionApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JamfProVersionApi' do
  before do
    # run before each test
    @api_instance = JamfPro::JamfProVersionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JamfProVersionApi' do
    it 'should create an instance of JamfProVersionApi' do
      expect(@api_instance).to be_instance_of(JamfPro::JamfProVersionApi)
    end
  end

  # unit tests for v1_jamf_pro_version_get
  # Return information about the Jamf Pro including the current version 
  # Returns information about the Jamf Pro including the current version. 
  # @param [Hash] opts the optional parameters
  # @return [JamfProVersion]
  describe 'v1_jamf_pro_version_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
