=begin
#Jamf Pro API

### Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

The version of the OpenAPI document: production

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for JamfPro::MobileDevicePrestagesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MobileDevicePrestagesApi' do
  before do
    # run before each test
    @api_instance = JamfPro::MobileDevicePrestagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MobileDevicePrestagesApi' do
    it 'should create an instance of MobileDevicePrestagesApi' do
      expect(@api_instance).to be_instance_of(JamfPro::MobileDevicePrestagesApi)
    end
  end

  # unit tests for v1_mobile_device_prestages_get
  # Search for sorted and paged Mobile Device Prestages 
  # Search for sorted and paged mobile device prestages
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :size 
  # @option opts [Integer] :pagesize 
  # @option opts [Integer] :page_size 
  # @option opts [String] :sort Sorting criteria in the format: property:asc/desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort&#x3D;date:desc,name:asc 
  # @return [MobileDevicePrestageSearchResults]
  describe 'v1_mobile_device_prestages_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_id_attachments_delete
  # Remove an attachment for a Mobile Device Prestage 
  # Remove an attachment for a Mobile Device Prestage
  # @param id Mobile Device Prestage identifier
  # @param file_attachment_delete 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_mobile_device_prestages_id_attachments_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_id_attachments_get
  # Get attachments for a Mobile Device Prestage 
  # Get attachments for a Mobile Device Prestage
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<FileAttachment>]
  describe 'v1_mobile_device_prestages_id_attachments_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_id_attachments_post
  # Add an attachment to a Mobile Device Prestage 
  # Add an attachment to a Mobile Device prestage
  # @param id Identifier of the Mobile Device Prestage the attachment should be assigned to
  # @param file The file to upload
  # @param [Hash] opts the optional parameters
  # @return [PrestageFileAttachment]
  describe 'v1_mobile_device_prestages_id_attachments_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_id_delete
  # Delete a Mobile Device Prestage with the supplied id 
  # Deletes a Mobile Device Prestage with the supplied id
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_mobile_device_prestages_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_id_get
  # Retrieve a Mobile Device Prestage with the supplied id 
  # Retrieves a Mobile Device Prestage with the supplied id
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @return [GetMobileDevicePrestage]
  describe 'v1_mobile_device_prestages_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_id_history_get
  # Get sorted and paged Mobile Device Prestage history objects 
  # Gets sorted and paged mobile device prestage history objects
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :size 
  # @option opts [Integer] :pagesize 
  # @option opts [Integer] :page_size 
  # @option opts [Array<String>] :sort Sorting criteria in the format: property,asc/desc. Default sort order is descending. Multiple sort criteria are supported and must be entered on separate lines in Swagger UI. In the URI the &#39;sort&#39; query param is duplicated for each sort criterion, e.g., ...&amp;sort&#x3D;name%2Casc&amp;sort&#x3D;date%2Cdesc
  # @return [HistorySearchResults]
  describe 'v1_mobile_device_prestages_id_history_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_id_history_post
  # Add Mobile Device Prestage history object notes 
  # Adds mobile device prestage history object notes
  # @param id Mobile Device Prestage identifier
  # @param object_history_note History notes to create
  # @param [Hash] opts the optional parameters
  # @return [ObjectHistory]
  describe 'v1_mobile_device_prestages_id_history_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_id_put
  # Update a Mobile Device Prestage 
  # Updates a Mobile Device Prestage
  # @param id Mobile Device Prestage identifier
  # @param put_mobile_device_prestage Mobile Device Prestage to update
  # @param [Hash] opts the optional parameters
  # @return [GetMobileDevicePrestage]
  describe 'v1_mobile_device_prestages_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_id_scope_delete
  # Remove Device Scope for a specific Mobile Device Prestage 
  # Remove device scope for a specific mobile device prestage
  # @param id Mobile Device Prestage identifier
  # @param prestage_scope_update Serial Numbers to remove from scope
  # @param [Hash] opts the optional parameters
  # @return [PrestageScopeResponse]
  describe 'v1_mobile_device_prestages_id_scope_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_id_scope_get
  # Get Device Scope for a specific Mobile Device Prestage 
  # Get device scope for a specific mobile device prestage
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @return [PrestageScopeResponse]
  describe 'v1_mobile_device_prestages_id_scope_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_id_scope_post
  # Add Device Scope for a specific Mobile Device Prestage 
  # Add device scope for a specific mobile device prestage
  # @param id Mobile Device Prestage identifier
  # @param prestage_scope_update Serial Numbers to scope
  # @param [Hash] opts the optional parameters
  # @return [PrestageScopeResponse]
  describe 'v1_mobile_device_prestages_id_scope_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_id_scope_put
  # Replace Device Scope for a specific Mobile Device Prestage 
  # Replace device scope for a specific mobile device prestage
  # @param id Mobile Device Prestage identifier
  # @param prestage_scope_update Serial Numbers to scope
  # @param [Hash] opts the optional parameters
  # @return [PrestageScopeResponse]
  describe 'v1_mobile_device_prestages_id_scope_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_post
  # Create a Mobile Device Prestage 
  # Create a mobile device prestage
  # @param mobile_device_prestage Mobile Device Prestage to create. ids defined in this body will be ignored
  # @param [Hash] opts the optional parameters
  # @return [GetMobileDevicePrestage]
  describe 'v1_mobile_device_prestages_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_scope_get
  # Get all Device Scope for all Mobile Device Prestages 
  # Get all device scope for all mobile device prestages
  # @param [Hash] opts the optional parameters
  # @return [PrestageScope]
  describe 'v1_mobile_device_prestages_scope_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_sync_get
  # Get all Prestage sync States for all prestages 
  # Get all prestage sync states for all prestages
  # @param [Hash] opts the optional parameters
  # @return [Array<PrestageSyncStatus>]
  describe 'v1_mobile_device_prestages_sync_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_sync_id_get
  # Get all prestage sync states for a single prestage 
  # Get all prestage sync states for a single prestage
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<PrestageSyncStatus>]
  describe 'v1_mobile_device_prestages_sync_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_mobile_device_prestages_sync_id_latest_get
  # Get the latest Sync State for a single Prestage 
  # Get the latest sync state for a single prestage
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @return [PrestageSyncStatus]
  describe 'v1_mobile_device_prestages_sync_id_latest_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_get
  # Get sorted and paged Mobile Device Prestages 
  # Gets sorted and paged mobile device prestages
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [Array<String>] :sort Sorting criteria in the format: property:asc/desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort&#x3D;date:desc,name:asc 
  # @return [MobileDevicePrestageSearchResultsV2]
  describe 'v2_mobile_device_prestages_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_attachments_delete_multiple_post
  # Remove an attachment for a Mobile Device Prestage 
  # Remove an attachment for a Mobile Device Prestage
  # @param id Mobile Device Prestage identifier
  # @param ids 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_mobile_device_prestages_id_attachments_delete_multiple_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_attachments_get
  # Get attachments for a Mobile Device Prestage 
  # Get attachments for a Mobile Device Prestage
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<FileAttachmentV2>]
  describe 'v2_mobile_device_prestages_id_attachments_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_attachments_post
  # Add an attachment to a Mobile Device Prestage 
  # Add an attachment to a Mobile Device prestage
  # @param id Identifier of the Mobile Device Prestage the attachment should be assigned to
  # @param file The file to upload
  # @param [Hash] opts the optional parameters
  # @return [PrestageFileAttachmentV2]
  describe 'v2_mobile_device_prestages_id_attachments_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_delete
  # Delete a Mobile Device Prestage with the supplied id 
  # Deletes a Mobile Device Prestage with the supplied id
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_mobile_device_prestages_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_get
  # Retrieve a Mobile Device Prestage with the supplied id 
  # Retrieves a Mobile Device Prestage with the supplied id
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @return [GetMobileDevicePrestageV2]
  describe 'v2_mobile_device_prestages_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_history_get
  # Get sorted and paged Mobile Device Prestage history objects 
  # Gets sorted and paged mobile device prestage history objects
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [Array<String>] :sort Sorting criteria in the format: property,asc/desc. Default sort order is descending. Multiple sort criteria are supported and must be entered on separate lines in Swagger UI. In the URI the &#39;sort&#39; query param is duplicated for each sort criterion, e.g., ...&amp;sort&#x3D;name%2Casc&amp;sort&#x3D;date%2Cdesc
  # @return [HistorySearchResults]
  describe 'v2_mobile_device_prestages_id_history_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_history_post
  # Add Mobile Device Prestage history object notes 
  # Adds mobile device prestage history object notes
  # @param id Mobile Device Prestage identifier
  # @param object_history_note History notes to create
  # @param [Hash] opts the optional parameters
  # @return [HrefResponse]
  describe 'v2_mobile_device_prestages_id_history_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_put
  # Update a Mobile Device Prestage 
  # Updates a Mobile Device Prestage
  # @param id Mobile Device Prestage identifier
  # @param put_mobile_device_prestage_v2 Mobile Device Prestage to update
  # @param [Hash] opts the optional parameters
  # @return [GetMobileDevicePrestageV2]
  describe 'v2_mobile_device_prestages_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_scope_delete_multiple_post
  # Remove Device Scope for a specific Mobile Device Prestage 
  # Remove device scope for a specific mobile device prestage
  # @param id Mobile Device Prestage identifier
  # @param prestage_scope_update Serial Numbers to remove from scope
  # @param [Hash] opts the optional parameters
  # @return [PrestageScopeResponseV2]
  describe 'v2_mobile_device_prestages_id_scope_delete_multiple_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_scope_get
  # Get Device Scope for a specific Mobile Device Prestage 
  # Get device scope for a specific mobile device prestage
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @return [PrestageScopeResponseV2]
  describe 'v2_mobile_device_prestages_id_scope_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_scope_post
  # Add Device Scope for a specific Mobile Device Prestage 
  # Add device scope for a specific mobile device prestage
  # @param id Mobile Device Prestage identifier
  # @param prestage_scope_update Serial Numbers to scope
  # @param [Hash] opts the optional parameters
  # @return [PrestageScopeResponseV2]
  describe 'v2_mobile_device_prestages_id_scope_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_scope_put
  # Replace Device Scope for a specific Mobile Device Prestage 
  # Replace device scope for a specific mobile device prestage
  # @param id Mobile Device Prestage identifier
  # @param prestage_scope_update Serial Numbers to scope
  # @param [Hash] opts the optional parameters
  # @return [PrestageScopeResponseV2]
  describe 'v2_mobile_device_prestages_id_scope_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_syncs_get
  # Get all prestage sync states for a single prestage 
  # Get all prestage sync states for a single prestage
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<PrestageSyncStatusV2>]
  describe 'v2_mobile_device_prestages_id_syncs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_id_syncs_latest_get
  # Get the latest Sync State for a single Prestage 
  # Get the latest sync state for a single prestage
  # @param id Mobile Device Prestage identifier
  # @param [Hash] opts the optional parameters
  # @return [PrestageSyncStatusV2]
  describe 'v2_mobile_device_prestages_id_syncs_latest_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_post
  # Create a Mobile Device Prestage 
  # Create a mobile device prestage
  # @param mobile_device_prestage_v2 Mobile Device Prestage to create. ids defined in this body will be ignored
  # @param [Hash] opts the optional parameters
  # @return [HrefResponse]
  describe 'v2_mobile_device_prestages_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_scope_get
  # Get all Device Scope for all Mobile Device Prestages 
  # Get all device scope for all mobile device prestages
  # @param [Hash] opts the optional parameters
  # @return [PrestageScopeV2]
  describe 'v2_mobile_device_prestages_scope_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_mobile_device_prestages_syncs_get
  # Get all Prestage sync States for all prestages 
  # Get all prestage sync states for all prestages
  # @param [Hash] opts the optional parameters
  # @return [Array<PrestageSyncStatusV2>]
  describe 'v2_mobile_device_prestages_syncs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
