=begin
#Jamf Pro API

### Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

The version of the OpenAPI document: production

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for JamfPro::SelfServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SelfServiceApi' do
  before do
    # run before each test
    @api_instance = JamfPro::SelfServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SelfServiceApi' do
    it 'should create an instance of SelfServiceApi' do
      expect(@api_instance).to be_instance_of(JamfPro::SelfServiceApi)
    end
  end

  # unit tests for v1_self_service_settings_get
  # Get an object representation of Self Service settings 
  # gets an object representation of Self Service settings 
  # @param [Hash] opts the optional parameters
  # @return [SelfServiceSettings]
  describe 'v1_self_service_settings_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_self_service_settings_put
  # Put an object representation of Self Service settings 
  # puts an object representation of Self Service settings 
  # @param self_service_settings object that contains all editable global fields to alter Self Service settings 
  # @param [Hash] opts the optional parameters
  # @return [SelfServiceSettings]
  describe 'v1_self_service_settings_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
