=begin
#Jamf Pro API

### Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

The version of the OpenAPI document: production

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for JamfPro::DeviceCommunicationSettings
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe JamfPro::DeviceCommunicationSettings do
  let(:instance) { JamfPro::DeviceCommunicationSettings.new }

  describe 'test an instance of DeviceCommunicationSettings' do
    it 'should create an instance of DeviceCommunicationSettings' do
      expect(instance).to be_instance_of(JamfPro::DeviceCommunicationSettings)
    end
  end
  describe 'test attribute "auto_renew_mobile_device_mdm_profile_when_ca_renewed"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "auto_renew_mobile_device_mdm_profile_when_device_identity_cert_expiring"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "auto_renew_computer_mdm_profile_when_ca_renewed"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "auto_renew_computer_mdm_profile_when_device_identity_cert_expiring"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "mdm_profile_mobile_device_expiration_limit_in_days"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Integer', [90, 120, 180])
      # validator.allowable_values.each do |value|
      #   expect { instance.mdm_profile_mobile_device_expiration_limit_in_days = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "mdm_profile_computer_expiration_limit_in_days"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Integer', [90, 120, 180])
      # validator.allowable_values.each do |value|
      #   expect { instance.mdm_profile_computer_expiration_limit_in_days = value }.not_to raise_error
      # end
    end
  end

end
