=begin
#Jamf Pro API

### Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

The version of the OpenAPI document: production

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for JamfPro::PatchPolicyOnDashboard
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe JamfPro::PatchPolicyOnDashboard do
  let(:instance) { JamfPro::PatchPolicyOnDashboard.new }

  describe 'test an instance of PatchPolicyOnDashboard' do
    it 'should create an instance of PatchPolicyOnDashboard' do
      expect(instance).to be_instance_of(JamfPro::PatchPolicyOnDashboard)
    end
  end
  describe 'test attribute "is_on_dashboard"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
